# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8457bfc2df760cc855c3e3a26ece1676c4c48edd25e14791ad374c1730214adc2e2b1c322a5e76ae16692e7148b8233d6a87028bb06b2af5d7950470aa585ae6

test:
  secret_key_base: ea4f811ff720e34947566a7eb808a0e6679df449f79d46ee25938131bdb48d6af8d63db680eb1eaa084ebf9f2b4dce46356d4f805b07d455fb8d3e4ef2de3f39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
